language: php

os:
  - linux

php:
    - 5.6
    - 7.0

sudo: false

# Disable x-debug to speed up things
before_install: phpenv config-rm xdebug.ini

# Install codeception
install:
  - echo "Download and Install codecept.phar"
  - wget -c -nc --retry-connrefused --tries=0 http://codeception.com/codecept.phar
  - chmod +x codecept.phar
  - php codecept.phar --version

# Execute tests
script:
  - cd web/protected/tests
  - php codecept.phar run unit --no-interaction

branches:
  only: master
